# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

language: zh-cn
timezone: Asia/Shanghai

# Site
# 博客的标题
title: 巴比龙科技组

# banner显示的子标题
subtitle: 巴比龙科技组

# banner显示的简短介绍
subtitle_desc: 享受生命，享受自由

# seo关键字
keywords: 巴比龙, AI, 信息技术, 科技组, 程序员, 前端开发, 全栈开发, Python, Java

# 博客介绍（同时用于seo）
description: 有一些鸟儿是注定不会被关在笼子里，它们的每一片羽毛都闪耀着自由的光辉。

# 个人介绍
introduction: Enjoy your freedom！

# 博客的favicon图标，支持本地及在线两种方式，本地请将图标放置于 themes/hexo-theme-skapp/source/img 目录下
favicon_ico: https://papillon-1258009638.cos.ap-guangzhou.myqcloud.com/favicon.ico

# 博客的左上角logo图标，支持本地及在线两种方式
logo: http://oo12ugek5.bkt.clouddn.com/images/logo-text-white.png

# 头像/二维码（用于显示在底部）二选一
avatar: https://papillon-1258009638.cos.ap-guangzhou.myqcloud.com/qrcode_for_gh_643034dd3fff_258.jpg
# qrcode: https://papillon-1258009638.cos.ap-guangzhou.myqcloud.com/qrcode_for_gh_643034dd3fff_258.jpg

# 文章的默认封面
default_cover: https://papillon-1258009638.cos.ap-guangzhou.myqcloud.com/144555tabhxlb0qo5a8ki0.jpeg

# header 的背景图
header_cover: https://papillon-1258009638.cos.ap-guangzhou.myqcloud.com/194530quuhqbh5xu0b7zuk.jpg

# 404 页面的背景图
error_page_bg: https://papillon-1258009638.cos.ap-guangzhou.myqcloud.com/404.png

# 页面加载loading图标
loader_img: https://papillon-1258009638.cos.ap-guangzhou.myqcloud.com/loading.gif

# 站长信息
author: Lucius Woo
link: https://github.com/ukonwho

# 用于页面 footer 的站长信息
about:
  info: 巴比龙科技组，一个追求自由的科技工作组，这里有信息技术知识分享，有技术课程学习，欢迎点击右下角订阅 rss。
  address: Shenzhen, Guangdong Province, China
  email: luciuswoo@qq.com
  
# Busuanzi
busuanzi: true

# Feed Atom
feed:
  type: atom
  path: atom.xml
  limit: 20

# Sitemap
sitemap:
  path: sitemap.xml

menu:
  home: / 
  archive: /archives
  about: /about
  search: /search


# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://www.papillondev.com/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: skapp

Plugins:
- hexo-generator-cname

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/ukonwho/ukonwho.github.io.git
  branch: master
